name: Android
on: workflow_dispatch
jobs:
  Build-clang:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r25c
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.0
      - name: Restore Previous Cache
        if: ${{ always() }}
        id: cache-debug-build-android-restore-clang
        uses: actions/cache/restore@main
        with:
          path: |
            ~/.hxcpp
            ~/haxelib
            ~/.gradle
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build-clang
      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib git extension-androidtools https://github.com/mcagabe19-stuff/extension-androidtools.git
          haxelib install flixel-addons 3.0.2 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install flixel 5.2.2 --quiet
          haxelib git hxCodec https://github.com/mcagabe19-stuff/hxCodec.git
          # haxelib install hscript --quiet
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
          haxelib install lime 8.0.1 --quiet
          haxelib git linc_luajit https://github.com/mcagabe19-stuff/linc_luajit.git
          haxelib install openfl 9.2.1 --quiet
          haxelib install SScript 5.0.0 --quiet
          haxelib install tjson 1.4.0 --quiet
          haxelib git extension-orientation https://github.com/HaxeExtension/extension-orientation.git
      - name: Setup git hxcpp
        run: |
          cd $(haxelib libpath hxcpp)/tools/hxcpp
          haxe compile.hxml
          cd ${{ github.workspace }}
      - name: Info
        run: haxe --version && haxelib list
      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Compile
        run: haxelib run lime build android -D GRADLE7 -release
        env:
          HXCPP_COMPILE_CACHE: ~/.hxcpp
          cert_pass: nullfunni
          cert_alias_pass: nullfunni
      - name: Clear Previous Cache
        if: ${{ always() }}
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-android-build-clang") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }
      - name: Save Current Cache
        if: ${{ always() }}
        id: cache-release-build-android-save-clang
        uses: actions/cache/save@main
        with:
          path: |
            ~/.hxcpp
            ~/haxelib
            ~/.gradle
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build-clang
      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: androidBuild-clang
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
