name: iOS
on: [workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@master
        with:
          xcode-version: '12.4'
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install flixel-addons 3.0.2 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install flixel 5.2.2 --quiet
          haxelib git hxCodec https://github.com/mcagabe19-stuff/hxCodec.git
          # haxelib install hxcpp-debug-server 1.2.4 --quiet
          # haxelib install hscript --quiet
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp.git
          haxelib git lime https://github.com/mcagabe19-stuff/lime7.9.0-arm.git
          haxelib git linc_luajit https://github.com/mcagabe19-stuff/linc_luajit.git
          haxelib install openfl 9.2.1 --quiet
          haxelib install SScript 5.0.0 --quiet
          # haxelib install tjson 1.4.0 --quiet
          haxelib git extension-orientation https://github.com/HaxeExtension/extension-orientation.git
      - name: Rebuild Libs
        run: |
          # haxelib run lime rebuild mac -64 -release # && ln -s /Users/runner/haxelib/lime/git/ndll/iPhone/liblime.iphoneos-64.a /Users/runner/haxelib/lime/git/ndll/iPhone/liblime.iphoneos.a
          haxelib run lime rebuild extension-orientation ios -arm64 -release && ln -s /Users/runner/haxelib/extension-orientation/git/ndll/iPhone/libes_orientation.iphoneos-64.a /Users/runner/haxelib/extension-orientation/git/ndll/iPhone/libes_orientation_legacy.iphoneos.a
      - name: Compile
        continue-on-error: true
        run: haxelib run lime build ios -release -arm64
        # env:
          # CODE_SIGN_ENTITLEMENTS: ""
          # CODE_SIGNING_ALLOWED: "NO"
      - name: Compile 2
        run: cd export/release/ios && /Applications/Xcode_12.4.app/Contents/Developer/usr/bin/xcodebuild CODE_SIGN_ENTITLEMENTS="" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" -configuration Release PLATFORM_NAME=iphoneos SDKROOT=iphoneos14.4 -arch arm64 -project PsychEngine.xcodeproj -allowProvisioningUpdates -allowProvisioningDeviceRegistration clean build
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: iOS-Source
          path: 'export/release/ios'
