name: let's fuck karim's laptop
on: workflow_dispatch
jobs:
  Build:
    runs-on: self-hosted
    permissions: write-all

    steps:
      - name: Info
        run: echo haxe --version && haxelib list
        
      - name: Changing Directory
        run: cd C:\Users\LENOVO\Desktop\GitHub\FNF-PsychEngine-Mobile

      - name: Compile
        run: lime build android -release -D NO_PRECOMPILED_HEADERS
        env:
          cert_pass: nullfunni
          cert_alias_pass: nullfunni

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: warn
